// Generated by CoffeeScript 1.6.2
(function() {
  var dataAll, dataGet, dataSet, defaultOptions, strings, translate,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty;

  strings = {};

  dataSet = function(el, key, value) {
    return el.setAttribute("data-t7e-" + (key.toLowerCase()), value);
  };

  dataGet = function(el, key) {
    return el.getAttribute("data-t7e-" + (key.toLowerCase()));
  };

  dataAll = function(el) {
    var attr, data, _i, _len, _ref;

    data = {};
    _ref = el.attributes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      attr = _ref[_i];
      if ((attr.name.indexOf('data-t7e-')) !== 0) {
        continue;
      }
      data[attr.name.slice('data-t7e-'.length)] = attr.value;
    }
    return data;
  };

  defaultOptions = {
    raw: false,
    literal: false,
    fallback: null
  };

  translate = function() {
    var className, classNames, dataAttribute, element, key, literal, object, options, outer, property, raw, result, segment, segments, tag, value, variable, _arg, _i, _j, _k, _len, _len1, _ref, _ref1;

    _arg = 3 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 2) : (_i = 0, []), key = arguments[_i++], options = arguments[_i++];
    tag = _arg[0];
    if (options == null) {
      options = {};
    }
    if (typeof options === 'string') {
      _ref = __slice.call(arguments).concat([{}]), tag = _ref[0], key = _ref[1], options = _ref[2];
    }
    if (tag != null) {
      _ref1 = tag.split('.'), tag = _ref1[0], classNames = 2 <= _ref1.length ? __slice.call(_ref1, 1) : [];
      element = document.createElement(tag);
      for (_j = 0, _len = classNames.length; _j < _len; _j++) {
        className = classNames[_j];
        element.classList.add(className);
      }
      dataSet(element, 'key', key || '');
      for (property in options) {
        value = options[property];
        dataAttribute = (property.charAt(0)) === '$' ? "var-" + property.slice(1) : !(property in defaultOptions) ? "attr-" + property : "opt-" + property;
        dataSet(element, dataAttribute, value);
      }
      translate.refresh(element);
      raw = options.raw != null ? options.raw : defaultOptions.raw;
      if (raw) {
        return element;
      } else {
        outer = document.createElement('div');
        outer.appendChild(element);
        return outer.innerHTML;
      }
    } else {
      segments = key.split('.');
      object = strings;
      for (_k = 0, _len1 = segments.length; _k < _len1; _k++) {
        segment = segments[_k];
        if (object != null) {
          object = object[segment];
        }
      }
      if (object instanceof Array) {
        object = object.join('\n');
      }
      result = object || options.fallback || key;
      literal = options.literal != null ? options.literal : defaultOptions.literal;
      if (!literal) {
        for (variable in options) {
          value = options[variable];
          if ((variable.charAt(0)) === '$') {
            result = result.replace(variable, value, 'gi');
          }
        }
      }
      return result;
    }
  };

  translate.refresh = function(root, givenOptions) {
    var attrName, dataAttr, element, key, keyedElements, optName, options, property, value, varName, _i, _len, _ref;

    if (root == null) {
      root = document.body;
    }
    if (givenOptions == null) {
      givenOptions = {};
    }
    keyedElements = Array.prototype.slice.call(root.querySelectorAll('[data-t7e-key]'));
    if ((dataGet(root, 'key')) != null) {
      keyedElements.unshift(root);
    }
    options = {};
    for (property in givenOptions) {
      value = givenOptions[property];
      options[property] = value;
    }
    for (_i = 0, _len = keyedElements.length; _i < _len; _i++) {
      element = keyedElements[_i];
      key = dataGet(element, 'key');
      _ref = dataAll(element);
      for (dataAttr in _ref) {
        value = _ref[dataAttr];
        if ((dataAttr.indexOf('var-')) === 0) {
          varName = dataAttr.slice('var-'.length);
          options["$" + varName] = value;
        } else if ((dataAttr.indexOf('attr-')) === 0) {
          attrName = dataAttr.slice('attr-'.length);
          options[attrName] = value;
        } else if ((dataAttr.indexOf('opt-')) === 0) {
          optName = dataAttr.slice('opt-'.length);
          options[optName] = value;
        }
      }
      element.innerHTML = translate(key, options);
      for (property in options) {
        value = options[property];
        if ((property.charAt(0)) === '$') {
          continue;
        }
        if (property in defaultOptions) {
          continue;
        }
        element.setAttribute(property, translate(value, options));
      }
    }
    return null;
  };

  translate.load = function(newStringSet, _base) {
    var key, value, _results;

    if (_base == null) {
      _base = strings;
    }
    _results = [];
    for (key in newStringSet) {
      if (!__hasProp.call(newStringSet, key)) continue;
      value = newStringSet[key];
      if ((typeof value === 'string') || (value instanceof Array)) {
        _results.push(_base[key] = value);
      } else {
        if (!(key in _base)) {
          _base[key] = {};
        }
        _results.push(translate.load(_base[key], value));
      }
    }
    return _results;
  };

  if (typeof window !== "undefined" && window !== null) {
    window.t7e = translate;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = translate;
  }

}).call(this);
